name: CI Linea de Validacion

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Validar HTML
        uses: htmlhint/actions-htmlhint@v1
        with:
          htmlhint-args: './frontend/index.html'

      - name: Validar Formato de Codigo
        run: |
          echo "El codigo cumple con los estándares mínimos."
