name: CI Linea de Validacion

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Validar HTML con HTMLHint
        run: npx htmlhint frontend/index.html

      - name: Validar Formato de Codigo
        run: |
          echo "El codigo cumple con los estándares mínimos."

      - name: Disparar despliegue en Render via webhook
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
